/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.subredes;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;


/**
 *
 * @author Primeiro PI
 */
public class Janela extends javax.swing.JFrame {
    
    //Declaração e atribuição do objeto "calc" que será usado para a comunicação com a classe "Calculo";
    Calculo calc = new Calculo();

    /**
     * Creates new form SubRedesUI
     */
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IPtext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Prefixotxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        Calcula = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        Sobre = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        info = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cálculo de Sub-rede");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Corbel", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Insira o IP:");

        IPtext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        IPtext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IPtext.setAlignmentX(0.0F);
        IPtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IPtextActionPerformed(evt);
            }
        });
        IPtext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IPtextKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Corbel", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Insira o prefixo:");

        Prefixotxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Prefixotxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Prefixotxt.setAlignmentX(0.0F);
        Prefixotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PrefixotxtKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Prefixotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IPtext, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IPtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Prefixotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel3, new java.awt.GridBagConstraints());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        Calcula.setFont(new java.awt.Font("Corbel", 3, 16)); // NOI18N
        Calcula.setText("Calcular");
        Calcula.setAlignmentX(45.0F);
        Calcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculaActionPerformed(evt);
            }
        });
        Calcula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CalculaKeyPressed(evt);
            }
        });

        Sair.setFont(new java.awt.Font("Corbel", 3, 16)); // NOI18N
        Sair.setText("Sair");
        Sair.setAlignmentX(45.0F);
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        Sair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SairKeyPressed(evt);
            }
        });

        Sobre.setFont(new java.awt.Font("Corbel", 3, 16)); // NOI18N
        Sobre.setText("Sobre");
        Sobre.setAlignmentX(45.0F);
        Sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreActionPerformed(evt);
            }
        });
        Sobre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SobreKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Calcula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sobre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Calcula)
                    .addComponent(Sair)
                    .addComponent(Sobre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel5.add(jPanel4, gridBagConstraints);

        jPanel1.add(jPanel5);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        info.setEditable(false);
        info.setBackground(new java.awt.Color(220, 220, 220));
        info.setColumns(20);
        info.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        info.setRows(5);
        info.setAutoscrolls(false);
        info.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                infoCaretUpdate(evt);
            }
        });
        jScrollPane2.setViewportView(info);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 992, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento de clicar no botão Calcula.
     * @param evt 
     */
    private void CalculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculaActionPerformed
        //Chama o método launch().
        launch();
    }//GEN-LAST:event_CalculaActionPerformed

    private void IPtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IPtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IPtextActionPerformed

   /**
    * Evento de clicar no botão Sobre.
    * @param evt 
    */
    private void SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreActionPerformed
        //Mensagem exibida com o nome dos integrantes do grupo.
//        JOptionPane.showMessageDialog(null, "Software desenvolvido por:\n"
//                + "João Netto Pinheiro\n"
//                + "João Paulo Nascimento Oliveira\n"
//                + "Paulo Roberto Vieira ","Sobre",JOptionPane.PLAIN_MESSAGE);
addInfo("\n\t\tSoftware desenvolvido por:\n\n"
                + "\t\tJoão Netto Pinheiro\n"
                + "\t\tJoão Paulo Nascimento Oliveira\n"
                + "\t\tPaulo Roberto Vieira ");
    }//GEN-LAST:event_SobreActionPerformed

    /**
     * Evento de clicar no botão Sair.
     * @param evt 
     */
    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void infoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_infoCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_infoCaretUpdate

    /**
     * Evento de teclas pressionadas no campo de entrada de prefixo.
     * @param evt 
     */
    private void PrefixotxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrefixotxtKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            //Se a tecla Enter for pressionada, o método launch é chamado.
            launch();
        }else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            //Se a tecla ESC for pressionada, o foco para o campo do IP.
            IPtext.requestFocus();
    }
    }//GEN-LAST:event_PrefixotxtKeyPressed

    /**
     * Evento de teclas pressionadas no botão Calcula.
     * @param evt 
     */
    private void CalculaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CalculaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            //Se a tecla Enter for pressionada, o método launch é chamado.
            launch();
        }
    }//GEN-LAST:event_CalculaKeyPressed

    /**
     * Evento de teclas pressionadas no campo de entrada de IP.
     * @param evt 
     */
    private void IPtextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IPtextKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            //Se a tecla Enter for pressionada, o foco é passado para o campo do prefixo.
            Prefixotxt.requestFocus();
        }else if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            //Se a tecla ESC for pressionada, o programa é encerrado.
            System.exit(0);
    }
    }//GEN-LAST:event_IPtextKeyPressed

    /**
     * Evento de teclas pressionadas no botão Sobre.
     * @param evt 
     */
    private void SobreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SobreKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            //Se a tecla Enter for pressionada, uma mensagem é exibida com o nome dos integrantes do grupo.
//            JOptionPane.showMessageDialog(null, "Software desenvolvido por:\n"
//                + "João Netto Pinheiro\n"
//                + "João Paulo Nascimento Oliveira\n"
//                + "Paulo Roberto Vieira ","Sobre",JOptionPane.PLAIN_MESSAGE);
addInfo("\n\t\tSoftware desenvolvido por:\n\n"
                + "\t\tJoão Netto Pinheiro\n"
                + "\t\tJoão Paulo Nascimento Oliveira\n"
                + "\t\tPaulo Roberto Vieira ");
        }
    }//GEN-LAST:event_SobreKeyPressed

    /**
     * Evento de teclas pressionadas no botão Sair.
     * @param evt 
     */
    private void SairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SairKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            //Se a tecla Enter for pressionada, o programa é encerrado.
            System.exit(0);
        }
    }//GEN-LAST:event_SairKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }
    public void launch(){
        
         info.setText("");
        if(calc.VerificaIP(IPtext.getText()) == false || calc.VerificaPrefixo(Prefixotxt.getText()) == false){
            JOptionPane.showMessageDialog(null, "Erro nos parâmetros fornecidos. Revise-os","ERRO!", JOptionPane.ERROR_MESSAGE);
        }else{
            addInfo(calc.Retorno());
          
}
        
    }
    public void addInfo(String str){
        info.setText(str);
        info.setCaretPosition(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcula;
    private javax.swing.JTextField IPtext;
    private javax.swing.JTextField Prefixotxt;
    private javax.swing.JButton Sair;
    private javax.swing.JButton Sobre;
    private javax.swing.JTextArea info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables


}
